version: "1"
services:
  server:
    build: .
    container_name: approyal
    ports:
      - 3001:8080
    links:
      - database
    environment:
      DB_USER: approyal
      DB_PWD: zTBebkX2xny6ZJhT
      DB_HOST: approyal
      DB_PORT: 3306
  
  database:
    image: mysql:latest
    container_name: mysql
    environment:
        - name: "MYSQL_USER"
          value: "approyal"
        - name: "MYSQL_PASSWORD"
          value: "zTBebkX2xny6ZJhT"
        - name: "MYSQL_DATABASE"
          value: "approyal"
    volumes:
      - db:/var/lib/mysql/data
volumes:
  db: